version: '3.8'
services:
  i-risky-app:
    image: seraleu/i-risky-app:1.1.2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3838:3838"
    environment:
      - SERVER_PORT=3838
    container_name: i-risky-service