spring:
  h2:
    console:
      enabled: true
      path: /h2-irisky
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:irisky
    platform: h2
    driverClassName: org.h2.Driver
    username: sa
    password: