server:
  port: 3838

spring:
  ssl:
    bundle:
      pem:
        my-client:
          truststore:
            certificate: src/main/resources/certs/russian_trusted_sub_ca.cer
#  ssl:
#    bundle:
#      jks:
#        my-client:
#          truststore:
#            location:
#            password:
#            type: PKCS12
  application:
    name: irisky

  profiles:
    active: h2,telegram,giga

  liquibase:
    enabled: true
    change-log: classpath*:/db/changelog/main-changelog.xml

  h2:
    console:
      enabled: true

sber:
  llm:
    auth: