server:
  port: 3838

spring:
  application:
    name: irisky
  docker:
    compose:
      enabled: true
      file: docker-compose.yml
  ssl:
    bundle:
      pem:
        my-client:
          truststore:
            certificate: src/main/resources/certs/russian_trusted_sub_ca.cer
  profiles:
    active: h2,giga
  liquibase:
    enabled: true
    change-log: classpath*:/db/changelog/main-changelog.xml
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
        use-new-id-generator-mappings: false